<a href="https://colab.research.google.com/github/KavyaPremaseelan/Neural-Network/blob/main/Neural_Network_Scratch_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [3]:
y=np.array([[1],[0],[1]])
y

array([[1],
       [0],
       [1]])

# ***SIGMOID FUNCTION***

In [4]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [5]:
def derivative_sigmoid(x):
  return x*(1-x)

# ***INITIALIZING***

In [6]:
epoch=5000
lr=0.4
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [7]:
wh=np.random.uniform(size=(input_neurons,hidden_neurons))
bh=np.random.uniform(size=(1,hidden_neurons))
wo=np.random.uniform(size=(hidden_neurons,output_neurons))
bo=np.random.uniform(size=(1,output_neurons))

# ***TRAINING THE MODEL***

In [8]:
for i in range(epoch):
    # Forward Propagation
    # Hidden Layer
    hidden_layer_input = np.dot(x, wh) + bh
    hidden_layer_activation = sigmoid(hidden_layer_input)

    # Output Layer
    output_layer_input = np.dot(hidden_layer_activation, wo) + bo
    predicted_output = sigmoid(output_layer_input)

    # Backward Propagation
    # Calculate Error
    error = y - predicted_output

    # Calculate gradients at output layer
    slope_output_layer = derivative_sigmoid(predicted_output)
    delta_output = error * slope_output_layer

    # Calculate gradients at hidden layer
    error_hidden_layer = delta_output.dot(wo.T)
    slope_hidden_layer = derivative_sigmoid(hidden_layer_activation)
    delta_hidden = error_hidden_layer * slope_hidden_layer

    # Update Weights and Biases
    wo += hidden_layer_activation.T.dot(delta_output) * lr
    bo += np.sum(delta_output, axis=0, keepdims=True) * lr
    wh += x.T.dot(delta_hidden) * lr
    bh += np.sum(delta_hidden, axis=0, keepdims=True) * lr

In [9]:
print("Output after training:")
print(predicted_output)

Output after training:
[[0.98326953]
 [0.02100146]
 [0.98768992]]
