<a href="https://colab.research.google.com/github/KavyaPremaseelan/Neural-Network/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [3]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [6]:
print(mnist)

<module 'keras.api._v2.keras.datasets.mnist' from '/usr/local/lib/python3.10/dist-packages/keras/api/_v2/keras/datasets/mnist/__init__.py'>


In [4]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [7]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),#normalize
  tf.keras.layers.Dense(128, activation='relu'),#hidden layer
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [8]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-8.7309718e-01, -4.0105364e-01,  7.7967262e-01,  7.3873401e-02,
        -8.9363411e-02, -9.9613518e-02, -3.8821775e-01,  3.5382390e-01,
         3.3278915e-01,  8.5225701e-04]], dtype=float32)

In [9]:
tf.nn.softmax(predictions).numpy()

array([[0.03916917, 0.06279865, 0.20451878, 0.10097375, 0.0857661 ,
        0.08489148, 0.06360992, 0.13359477, 0.13081399, 0.09386329]],
      dtype=float32)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2982 - accuracy: 0.9130
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1422 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1090 - accuracy: 0.9669
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0886 - accuracy: 0.9720
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0744 - accuracy: 0.9765


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0696 - accuracy: 0.9781 - 570ms/epoch - 2ms/step


[0.06955385953187943, 0.9781000018119812]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.68420002e-07, 2.00015521e-07, 7.51248035e-06, 1.05646686e-04,
        1.40177558e-09, 9.23933214e-07, 1.16898774e-11, 9.99882340e-01,
        1.41809537e-07, 3.16536648e-06],
       [4.65495418e-07, 2.13754320e-04, 9.99718130e-01, 3.71857641e-05,
        2.67935606e-16, 2.83275294e-05, 2.70717976e-07, 5.85804517e-13,
        1.87105991e-06, 4.41356196e-12],
       [3.26638894e-09, 9.99731600e-01, 1.05342688e-05, 5.96756877e-07,
        6.09491281e-06, 2.55238376e-07, 5.31947535e-06, 1.52264751e-04,
        9.30478491e-05, 2.36346366e-07],
       [9.99546230e-01, 5.92670135e-09, 2.56076921e-04, 1.85643319e-06,
        3.94199446e-08, 3.64384250e-05, 1.35964190e-04, 3.53555805e-07,
        2.93561087e-08, 2.30837213e-05],
       [1.32373737e-06, 3.19839244e-09, 2.59084277e-06, 1.87263343e-08,
        9.97991562e-01, 2.07836663e-08, 9.36335937e-07, 1.38555930e-04,
        8.65390462e-07, 1.86415925e-03]], dtype=float32)>